### ISSUE TITLE
Kickstarter Shirt DLC

### ISSUE THREAD

**Issue by Kyzoku** [ketwaroo/KetwarooPortiaMod#1]
The Kickstarter Shirt DLC gets automatically deselected for me.  Is this intended behavior or a bug?

Also I just want to take a moment to thank you for the work you've done on this mod.  The GOG version that I have of this game is now so much better.

**Comment by ketwaroo** [comment]
Hello and thanks.

So this mod kind of forces the DLC to be actived while the map is loaded and running, it may not show accurate info on the main menu (DLC popup in bottom right). In the GOG version of the game that menu is pretty much useless and does nothing.

I originally wrote it only because I wanted the NPC outfits

If you reeeallly want that lousy tshirt, the games normally checks if a DLC is active whenever player enters their house. 

I retested it and the worked to obtain the lousy tshirt
 * exit house
 * use `Ctrl+F10` or whichever shortcut you have to open unity mod manager overlay,  enable lousy shirt DLC, save & close UMM
 * enter house to trigger DLC enabled check
 * exit house  to trigger mail delivery
 * collect letter from developers to obtain tshirt.

Another caveat is that the gog version doesn't seem to handle removing a DLC. Even though the overriden `IsDlcInstalled` method returns true/false based on the saved config, the game doesn't seem to take that into account if a DLC was enabled and it's state was saved in your save game. There might be some way to do it but I don't have plans to fix the game to that extent.

**Comment by Kyzoku** [comment]
Thank you for the explanation, I appreciate it.
